
spring.data.mongodb.uri=mongodb+srv://asiru:1234@cluster0.oyexbpi.mongodb.net/elephant?appName=Cluster0
#spring.data.mongodb.database=elephant

# JWT Secret (Keep this safe and make it long!)
app.jwtSecret=MySecretKeyThatIsAtLeast32CharactersLongForHS256Algorithm
app.jwtExpirationMs=86400000