
# JWT Secret (Keep this safe and make it long!)

app.jwtSecret=MySecretKeyThatIsAtLeast32CharactersLongForHS256Algorithm
app.jwtExpirationMs=86400000
server.port=8080
spring.jmx.enabled=false
spring.data.mongodb.auto-index-creation=false